config/routes.rb
Rails.application.routes.draw do
  match '/admin/movies' => 'movies#create', via: :post
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  get 'movies/detail' => 'movies#detail',as: :movies_detail
  resources :movies,:except => [:new, :delete,:edit,:update] do
    resources :comments
  end

  root to: "movies#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :movie
    validates_presence_of :body
end

app/models/movie.rb
class Movie < ApplicationRecord
  mount_uploader :image, MovieUploader
  has_many :views, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :users,through: :comments
  validates_presence_of :title,:genre,:plot,:image,:rating,:web
  validates :rating, numericality: { less_than_or_equal_to: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, UserUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :comments, dependent: :destroy
  has_many :movies, through: :comments
  validates_presence_of :name
  after_create :send_admin_mail
  def send_admin_mail
    UserMailer.welcome_email(self).deliver_now
  end

end

app/models/view.rb
class View < ApplicationRecord
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:image])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name,:image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  def create
   @comment = Comment.new(comment_params)
   @comment.user_id = current_user.id
   @comment.movie_id = params[:movie_id]
   if @comment.save
     Thread.new{
       @email = ReviewMail.new
       @m = Movie.find(params[:movie_id])
       @email.thankyou_mail(current_user,@m,@comment)


     }

     redirect_to movie_path(params[:movie_id]),notice: "Review add successfully"
   else
     redirect_to movie_path(params[:movie_id]),alert: "Review cannot Saved"
   end
 end

 private
   def comment_params
     params.require(:comment).permit(:body)
   end
end

app/controllers/concerns/other_service_call.rb
class OtherServiceCall
  def api_call(title)
    @title = title.split(' ').join('_')
    uri = URI("http://www.omdbapi.com/?t=#{@title}&apikey=c45185be")
    a = Net::HTTP.get(uri)
    b= JSON.parse(a)
    if b["Response"] == "True"
      title = b["Title"]
      year = b["Year"]
      image = b["Poster"]
      genre = b["Genre"].split(',').first
      plot = b["Plot"]
      if b["imdbRating"].split('/').second == nil
        rating = b["imdbRating"]
      else
        rating = b["imdbRating"]
      end
      web = b["Website"]
      cast = b["Actors"]
      return movie_create(title,year,image,genre,plot,rating,web,cast)
    else
      return false
    end
  end
  private
  def movie_create(title,year,image,genre,plot,rating,web,cast)
    @m = Movie.new
    @m.title = title
    @m.year = year
    @m.remote_image_url = image
    @m.genre = genre
    @m.plot =plot
    @m.rating = rating
    @m.web = web
    @m.cast = cast
    if @m.save
      return true
    else
      return false
    end
  end
end

app/controllers/concerns/review_mail.rb
class ReviewMail

  def thankyou_mail(user,movie,comment)
      ReviewMailer.thankyou_email(user,movie,comment).deliver_now
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :authenticate_admin_user!,only: [:create]
  before_action :set_id,except:[:index,:detail,:create]
  before_action :get_rating,only:[:index,:detail]
  before_action :get_view,only:[:index,:detail]

  def index
    @movies = Movie.all.order('created_at desc').limit(3)
    @movies_view = @movies_view.limit(4)
    @movies_rating = @movies_rating.limit(4)
  end

  def detail
    @view = params[:view]
     search = params[:search]
     if search
       capital_search = search.capitalize
       downcase_search = search.downcase
       upcase_search = search.upcase
       title_search = search.titleize
      @movies_rating = Movie.where("title like? OR title like? OR title like? OR title like?","#{capital_search}%","#{downcase_search}%","#{upcase_search}%","#{title_search}%").order('rating ASC')
      @movies_view = Movie.select("movies.*, COUNT(*) AS group_count").joins(:views).joins("JOIN views rg on rg.movie_id = views.movie_id").group('movies.id').where(id: @movies_rating.ids).order('group_count DESC')
    else
    end

  end

  def create

    if params[:view] =="automatic"
      @mv = OtherServiceCall.new.api_call(params[:movie][:title])
      if @mv == true
        redirect_to "#{ Rails.application.secrets.url}/admin/movies",notice: "movie Successfully Saved"
      else
        redirect_to new_admin_movie_path(view: params[:view]),alert: "Movie Not Found Please verify it."
      end
    else
      @movies =  Movie.new(movie_params)
      if @movies.save
        redirect_to "#{ Rails.application.secrets.url}/admin/movies",notice: "movie Successfully Saved"
      else
        redirect_to new_admin_movie_path
      end
    end
  end

  def show
    View.create(movie_id: @movies.id)
    @movies_list = Movie.where(genre: @movies.genre).order('rating Desc')
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def movie_params
    params.require(:movie).permit(:title,:image,:genre,:plot,:rating,:web,:year,:cast)
  end

  def set_id
    @movies = Movie.find(params[:id])
  end
  def get_view
    @movies_view = Movie.select("movies.*, COUNT(*) AS group_count").joins(:views).joins("JOIN views rg on rg.movie_id = views.movie_id").group('movies.id').order('group_count DESC')
  end
  def get_rating
    @movies_rating = Movie.all.order('rating desc')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def set_attribute(movies,no)
    case no
    when "second"
      if movies.second.present?
        return movies.second
      else
        return movies.last
      end
    when "third"
      if movies.third.present?
        return movies.third
      else
        return movies.last
      end
    end
  end
  def rating_active?(view)
    if view == "rating"
      return "active"
    elsif view == "views"
    else
      return "active"
    end
  end
  def view_active?(view)
    if view == "views"
      return "active"
    else
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class= "container">
    <div class="row">
  		<div class="col-md-12">
        <%= render 'shared/header'%>
        <%= render 'shared/notification'%>
        <%= yield %>
      </div>

    </div>
    <%= render 'shared/footer'%>
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'login', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "login" %>

  </head>

  <body>
        <%= render 'shared/notification'%>
        <%= yield %>
  </body>
</html>

app/views/movies/_form.html.erb
<%@movies = movies%>
<%= form_for @movies do |f| %>
<% if @movies.errors.any? %>
  <% @movies.errors.full_messages.each do |error| %>
  <div class="alert alert-danger alert-dismissable">
   <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
   <strong><%= error%></strong>
  </div>
  <% end%>
  <%end%>

  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2">
      Title
    </label>
    <div class="col-sm-10">
      <%= f.text_field :title, class: "form-control", required: true %>
    </div>
  </div>
  <% if view == "automatic" %>
  <%= hidden_field_tag 'view', view %>
  <%else%>
  <%= hidden_field_tag 'view', view %>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2">
        Poster
      </label>
      <div class="col-sm-10">
        <%= f.file_field :image, class: "form-control", required: true %>
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2">
        genre
      </label>
      <div class="col-sm-10">
        <%= f.text_field :genre, class: "form-control", required: true %>
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2">
        Plot
      </label>
      <div class="col-sm-10">
        <%= f.text_area :plot, class: "form-control", required: true %>
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2">
        Cast
      </label>
      <div class="col-sm-10">
        <%= f.text_area :cast, class: "form-control", required: true %>
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2">
        year
      </label>
      <div class="col-sm-10">
        <%= f.date_field :year, as: :year,style: "width:79% !important;"%>
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2">
        Rating
      </label>
      <div class="col-sm-10">
        <%= f.number_field :rating, class: "form-control", required: true %>
      </div>
    </div>
    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2">
        Website
      </label>
      <div class="col-sm-10">
        <%= f.text_field :web, class: "form-control", required: true %>
      </div>
    </div>
  <%end%>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Add new Moviews",class: "btn btn-success btn-block",style: "margin-top: 20px;"%>
    </div>
  </div>
  <%end%>

app/views/movies/_index_div.html.erb
<%
  first = movies.first
  second = set_attribute(movies,"second")
  third = set_attribute(movies,"third")
  fourth = movies.last
%>
<div class="row">
  <div class="col-md-3">
    <a href="<%= movie_path(first)%>">
    <img alt="Bootstrap Image Preview" src="<%= first.image_url%>" class="img-rounded image-setting-index" />
  </a>
    <h3 class="text-center text-info">
      <%= first.title.titleize%>
    </h3>
  </div>
  <div class="col-md-3">
    <a href="<%= movie_path(second)%>">
      <img alt="Bootstrap Image Preview" src="<%= second.image_url%>" class="img-rounded image-setting-index" />
    </a>
    <h3 class="text-center text-info">
      <%= second.title.titleize%>
    </h3>
  </div>
  <div class="col-md-3">
    <a href="<%= movie_path(third)%>">
      <img alt="Bootstrap Image Preview" src="<%= third.image_url%>" class="img-rounded image-setting-index" />
    </a>
    <h3 class="text-center text-info">
      <%= third.title.titleize%>
    </h3>
  </div>
  <div class="col-md-3">
    <a href="<%= movie_path(fourth)%>">
      <img alt="Bootstrap Image Preview" src="<%= fourth.image_url%>" class="img-rounded image-setting-index" />
    </a>
    <h3 class="text-center text-info">
      <%= fourth.title.titleize%>
    </h3>
  </div>
</div>

app/views/movies/_movie_comment.html.erb
<div class="col-md-12">

  <h3>Reviews(<%= @movies.comments.length %>)</h3>
  <%= form_for([movies, movies.comments.new],class:"form-inline") do |f| %>

    <div class="form-group">
      <% if user_signed_in?%>
        <%if current_user.image.present? %>
        <img alt="<% movies.title %>" src="<%= current_user.image_url %>" class="img-thumbnail user-img-img-show" align="middle"/>
        <%else%>
        <%= image_tag "avatar.png",id: "blah",class: "img-thumbnail user-img-img-show",align:"middle" %>
        <% end%>
      <% else %>
        <%= image_tag "avatar.png",id: "blah",class: "img-thumbnail user-img-img-show",align:"middle" %>
      <% end%>

      <%= f.text_area :body,class: "comment-box" %>
    </div>
      <div class="form-group comment-show">

      <%= f.submit "submit",class: "btn btn-primary" %>
    </div>
  <% end %>

</div>

app/views/movies/_movie_comment_show.html.erb
<div class="modal fade" id="exampleModalLong" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h3 class="modal-title" id="exampleModalLongTitle" style="text-align: center;">Reviews(<%= @movies.comments.length %>)</h3>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%movies.comments.order('created_at desc').each do |comment| %>
        <div class="col-md-3">
          <% if comment.user.image.present? %>
          <img alt="<% comment.user.name %>" src="<%= comment.user.image%>" class="img-thumbnail user-img-show" align="middle"/>
          <% else %>
            <%= image_tag "avatar.png",id: "blah",class: "img-thumbnail user-img-show",align:"middle" %>
          <% end%>
        </div>
        <div class="col-md-9 comment">
          <h3><%=  comment.user.name.titleize%></h3>
          <p>
            <%= comment.body%>
          </p>
        </div>

        <div class="clearfix"></div>
        </br>
        <%end%>
      </div>
      <div class="modal-footer" style="text-align:center;">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/movies/_movie_detail.html.erb
<div class="row">	<i>
  <div class="col-md-4">
    <img alt="<% movies.title %>" src="<%= movies.image_url %>" class="img-thumbnail title-show"/>
  </div>
  <div class="col-md-8">
    <div class= "col-md-4">
    <h3>
      <%= movies.title.titleize + " " + "(#{movies.year})"%>
    </h3>
      <div>
          <b><i>Genre:</i></b>

          <i><%= movies.genre %></i>
      </div>
  </div>
  <div class="col-md-4">
    <%= image_tag 'rating.png' ,class: "rating-show-image"%><h4 class= "rating-show"> <%= movies.rating %>/10</h4>
  </div>
  <div class="col-md-4"></div>
  <div class="col-md-12">
    <div>
      <h2>	Plot:</h2>

        <p><%= movies.plot%></p>
    </div>
  </div>
  <div class="col-md-12">
    <div>
      <h3>	Cast:</h3>

        <p><%= movies.cast%></p>
    </div>
  </div>
  <div class="col-md-12">
    <div>
        <a href="<%= movies.web%>" class="btn btn-primary web-show">Website</a>
    </div>
  </div>
  </div>
</div>

app/views/movies/_movie_top_list.html.erb
      <tr>
        <td>
          <%= index + 1 %>
        </td>
        <td>
        <a href="<%= movie_path(movies)%>" class="top-list">  <%= movies.title %> </a>
        </td>
        <td>
          <%= movies.genre %>
        </td>
      </tr>

app/views/movies/_slider.html.erb
<%
  first = movies.first
  second = set_attribute(movies,"second")
  third = movies.last
%>
<div class="carousel slide" id="carousel-687387">
  <ol class="carousel-indicators">
    <li class="active" data-slide-to="0" data-target="#carousel-687387">
    </li>
    <li data-slide-to="1" data-target="#carousel-687387">
    </li>
    <li data-slide-to="2" data-target="#carousel-687387">
    </li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <img alt="Carousel Bootstrap First" src="<%= first.image_url%>" class="slider-custom"/>
    </div>
    <div class="item">
      <img alt="Carousel Bootstrap Second" src="<%= second.image_url%>" class="slider-custom" />
    </div>
    <div class="item">
      <img alt="Carousel Bootstrap Third" src="<%= third.image_url%>" class="slider-custom" />
    </div>
  </div> <a class="left carousel-control" href="#carousel-687387" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-687387" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div>

app/views/movies/_slider_static.html.erb
<div class="carousel slide" id="carousel-687387">
  <ol class="carousel-indicators">
    <li class="active" data-slide-to="0" data-target="#carousel-687387">
    </li>
    <li data-slide-to="1" data-target="#carousel-687387">
    </li>
    <li data-slide-to="2" data-target="#carousel-687387">
    </li>
  </ol>
  <div class="carousel-inner">
    <div class="item active">
      <img alt="Carousel Bootstrap First" src="http://lorempixel.com/output/sports-q-c-1600-500-1.jpg" />
      <div class="carousel-caption">
        <h4>
          First Thumbnail label
        </h4>
        <p>
          Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
        </p>
      </div>
    </div>
    <div class="item">
      <img alt="Carousel Bootstrap Second" src="http://lorempixel.com/output/sports-q-c-1600-500-2.jpg" />
      <div class="carousel-caption">
        <h4>
          Second Thumbnail label
        </h4>
        <p>
          Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
        </p>
      </div>
    </div>
    <div class="item">
      <img alt="Carousel Bootstrap Third" src="http://lorempixel.com/output/sports-q-c-1600-500-3.jpg" />
      <div class="carousel-caption">
        <h4>
          Third Thumbnail label
        </h4>
        <p>
          Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.
        </p>
      </div>
    </div>
  </div> <a class="left carousel-control" href="#carousel-687387" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a> <a class="right carousel-control" href="#carousel-687387" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
</div>
<h3>
  Top Views Movies
</h3>
<div class="row">
  <div class="col-md-3">
    <img alt="Bootstrap Image Preview" src="http://lorempixel.com/140/140/" class="img-rounded image-setting-index" />
    <h3 class="text-center text-info">
      Avengers Infinity War
    </h3>
  </div>
  <div class="col-md-3">
    <img alt="Bootstrap Image Preview" src="http://lorempixel.com/140/140/" class="img-rounded image-setting-index" />
    <h3 class="text-center text-info">
      Avengers Infinity War
    </h3>
  </div>
  <div class="col-md-3">
    <img alt="Bootstrap Image Preview" src="http://lorempixel.com/140/140/" class="img-rounded image-setting-index" />
    <h3 class="text-center text-info">
      Avengers Infinity War
    </h3>
  </div>
  <div class="col-md-3">
    <img alt="Bootstrap Image Preview" src="http://lorempixel.com/140/140/" class="img-rounded image-setting-index" />
    <h3 class="text-center text-info">
      Avengers Infinity War
    </h3>
  </div>
</div>
<div class="top-rated-index">
  <h3>
    Top Rated Movies
  </h3>
  <div class="row">
    <div class="col-md-3">
      <img alt="Bootstrap Image Preview" src="http://lorempixel.com/140/140/" class="img-rounded image-setting-index" />
      <h3 class="text-center text-info">
        Avengers Infinity War
      </h3>
    </div>
    <div class="col-md-3">
      <img alt="Bootstrap Image Preview" src="http://lorempixel.com/140/140/" class="img-rounded image-setting-index" />
      <h3 class="text-center text-info">
        Avengers Infinity War
      </h3>
    </div>
    <div class="col-md-3">
      <img alt="Bootstrap Image Preview" src="http://lorempixel.com/140/140/" class="img-rounded image-setting-index" />
      <h3 class="text-center text-info">
        Avengers Infinity War
      </h3>
    </div>
    <div class="col-md-3">
      <img alt="Bootstrap Image Preview" src="http://lorempixel.com/140/140/" class="img-rounded image-setting-index" />
      <h3 class="text-center text-info">
        Avengers Infinity War
      </h3>
    </div>
  </div>
</div>

app/views/movies/detail.html.erb
<div class="col-md-12">
			<h3>
				Movies Details
			</h3>
			<div class="tabbable" id="tabs-467327">
				<ul class="nav nav-tabs">
					<li class="<%= rating_active?(@view)%>">
						<a href="#panel-827709" data-toggle="tab">By Ratings</a>
					</li>
					<li class="<%= view_active?(@view)%>">
						<a href="#panel-277598" data-toggle="tab">By Views</a>
					</li>
				</ul>
				<div class="tab-content">
					<div class="tab-pane <%= rating_active?(@view)%>" id="panel-827709">
						<% if @movies_rating.present? %>
							<div class="row">
                <% @movies_rating.each_slice(4) do |movies_rating| %>
  								<% movies_rating.each do |movies| %>
  								<div class="col-md-3">
  							    <a href="<%= movie_path(movies)%>">
  							             <img alt="Bootstrap Image Preview" src="<%= movies.image_url%>" class="img-rounded image-setting-index" />
  							    </a>
  							    <h3 class="text-center text-info">
  							      <%= movies.title.titleize%>
  							    </h3>
  							  </div>
  								<%end%>
                  <div style="clear:both;"></div>
                <%end%>
							</div>
						<% else%>
						<p>
							No Movie Present
						</p>
						<% end%>
					</div>
					<div class="tab-pane <%= view_active?(@view)%>" id="panel-277598">
						<% if @movies_view.present? %>
							<div class="row">
                <% @movies_view.each_slice(4) do |movies_view| %>
  								<% movies_view.each do |movies| %>
  								<div class="col-md-3">
  							    <a href="<%= movie_path(movies)%>">
  							    <img alt="Bootstrap Image Preview" src="<%= movies.image_url%>" class="img-rounded image-setting-index" />
  							  </a>
  							    <h3 class="text-center text-info">
  							      <%= movies.title.titleize%>
  							    </h3>
  							  </div>
  								<%end%>
                  <div style="clear:both;"></div>
                <%end%>
							</div>
						<% else%>
						<p>
							No Movie Present
						</p>
						<% end%>
					</div>
				</div>
			</div>
		</div>

app/views/movies/index.html.erb
<% if @movies.present? %>
  <%= render partial: "slider",locals: { movies: @movies} %>
<% else %>
<%= render partial: "slider_static" %>
<% end%>
<%if @movies_view.present? %>
  <h3>
    Top Views Movies
  </h3>
  <%= render partial: "index_div",locals: { movies: @movies_view} %>
  <div class="col-md-12">
    <%= link_to "Browse More",movies_detail_path(view: "views"), class: "browse-index"%>
  </div>
<% end %>
<% if @movies_rating.present? %>
    <div class="top-rated-index">
      <h3>
        Top Rated Movies
      </h3>
      <%= render partial: "index_div",locals: { movies: @movies_rating} %>
    </div>
    <div class="col-md-12">
      <%= link_to "Browse More",movies_detail_path(view: "rating"), class: "browse-index"%>
    </div>
<% end%>

app/views/movies/show.html.erb
<%= render partial: "movie_detail",locals: { movies: @movies} %>
<div class="row up-margin">
	<div class="col-md-12">
		<div class="row">
			<div class="col-md-6">

					<%if @movies.comments.present? %>
					<div class="row back-color">
					</br>

							<%@movies.comments.order('created_at desc').limit(3).reverse.each do |comment| %>
							<div class="col-md-3">
								<% if comment.user.image.present? %>
								<img alt="<% comment.user.name %>" src="<%= comment.user.image%>" class="img-thumbnail user-img-show" align="middle"/>
					      <% else %>
					        <%= image_tag "avatar.png",id: "blah",class: "img-thumbnail user-img-show",align:"middle" %>
					      <% end%>

							</div>
							<div class="col-md-9 comment">
								<h3><%=  comment.user.name.titleize%></h3>
								<p>
									<%= comment.body%>
								</p>
							</div>

							<div class="clearfix"></div>
							</br>
							<%end%>
							<div class="col-md-12">
								<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalLong" style="float: right;">
								  More Reviews
								</button>
							</div>
							<%= render partial: "movie_comment_show",locals: {movies: @movies}%>
						</div>
						<%else%>
						Be the first to comment
					<%end%>

				<div class="row">
								<%= render partial: "movie_comment",locals: { movies: @movies}  %>
				</div>
			</div>
			<div class="col-md-6">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<h4>Top 10 list of <%= @movies.genre%></h4>
						</h3>
					</div>
					<div class="panel-body table-responsive">
					  <table class="table">
					    <thead>
					      <tr>
					        <th>
					          #
					        </th>
					        <th>
					          Name
					        </th>
					        <th>
					          Genre
					        </th>
					      </tr>
					    </thead>
							<tbody>
								<% if @movies_list.present? %>
								<% @movies_list.each_with_index do |movie_list,index| %>

									<%= render partial: "movie_top_list",locals: { movies: movie_list,index: index} %>
									<%end%>
								<%else%>
								No Movie Present with this genre
								<%end%>
							</tbody>
							</table>
						</div>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/shared/_header.html.erb
<div class="page-header">
  <h1 class="header-setting">
    <%= link_to "Movies Store" , root_path,class: "heading" %>
  </h1>
</div>
<%= render 'shared/nav'%>

app/views/shared/_notification.html.erb
<% if flash[:error].present? %>
<div class="alert alert-error alert-dismissable">
 <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
 <strong><%= flash[:error] %></strong>
</div>
<% elsif flash[:alert].present?%>
<div class="alert alert-danger alert-dismissable">
 <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
 <strong><%= flash[:alert] %></strong>
</div>

<%elsif flash[:notice].present?%>
<div class="alert alert-success alert-dismissable">
 <a href="#" class="close" data-dismiss="alert" aria-label="close">×</a>
 <strong><%= flash[:notice] %></strong>
</div>

<%end%>

app/views/shared/_search.html.erb
<%= form_tag movies_detail_path, :method => 'get',class: "navbar-form navbar-left" do %>
  <div class="form-group">
    <%= text_field_tag :search, params[:search],class:"form-control",placeholder: "Find Movies" %>
  </div>
    <%= submit_tag "Search", :name => nil,class: "btn btn-default" %>
<% end %>